In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
from matplotlib import rcParams
rcParams['figure.figsize'] = 15,6

In [2]:
df = pd.read_csv('clientes_bet_aml_fraude.csv', sep=',', encoding='utf8')

In [3]:
df

,id_cliente,nome,sobrenome,email,telefone,data_cadastro,pais_registro,pais_ip_ultima_transacao,geolocalizacao_inconsistente,uso_vpn_proxy,...,flag_estruturacao,flag_multiplas_contas,flag_chip_dumping,flag_padrao_baixo_risco_lavagem,flag_saque_rapido,flag_suspeita_lavagem_dinheiro,status_investigacao,status_conta,pendente_validacao_documento,data_ultimo_alerta
0,1,Vitor,Ferreira,vitor.ferreira3033@outlook.com,(41) 99328-4419,2024-09-29,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Em análise,Não,NaN
1,2,Renata,Azevedo,renata.azevedo3881@hotmail.com,(47) 93523-5665,2025-03-27,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Inativo,Não,NaN
2,3,Beatriz,Azevedo Costa,beatriz.azevedo5364@outlook.com,(98) 99399-4124,2026-04-02,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Ativo,Sim,NaN
3,4,Nicolas,Teixeira Oliveira,nicolas.teixeira4172@outlook.com,(51) 92299-7466,2024-10-31,Panamá,Panamá,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Ativo,Não,NaN
4,5,Larissa,Oliveira,larissa.oliveira9626@terra.com.br,(71) 94163-6182,2024-05-02,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Ativo,Não,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,499996,Luana,Martins,luana.martins1953@icloud.com,(62) 99686-8927,2024-01-02,Paraguai,Paraguai,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Ativo,Não,NaN
499996,499997,Cláudio,Lima,claudio.lima4125@bol.com.br,(41) 92265-4877,2026-01-13,Malta,Malta,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Ativo,Sim,NaN
499997,499998,Amanda,Oliveira Cardoso,amanda.oliveira5138@bol.com.br,(71) 92239-7698,2024-02-24,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Ativo,Não,NaN
499998,499999,Luana,Campos,luana.campos531@bol.com.br,(31) 97364-6876,2025-01-26,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Inativo,Não,NaN
499999,500000,Paulo,Farias,paulo.farias2290@gmail.com,(98) 92621-4526,2025-12-18,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Inativo,Não,NaN

In [4]:
df.describe()

,id_cliente,numero_dispositivos_distintos,numero_contas_mesmo_dispositivo,numero_contas_mesmo_documento,numero_contas_mesmo_metodo_pagamento,numero_metodos_pagamento_distintos,valor_deposito_total,numero_depositos,valor_medio_deposito,numero_depositos_proximos_limite_declaracao,...,valor_ganho_cassino,valor_ganho_sportbook,razao_ganho_aposta_cassino,desvio_padrao_valor_aposta,numero_apostas_espelhadas,id_conta_relacionada_suspeita,bonus_usados,bonus_ganhos,numero_alertas_compliance,score_risco_aml
count,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,...,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000
mean,250000.500000,1.657840,1.246976,1.090766,1.202248,2.113228,1129.894588,11.555318,147.293951,0.406556,...,516.872711,355.844237,0.922913,172.148850,0.961048,16180.111442,67.217675,27.526113,0.299172,7.136015
std,144337.711634,0.970031,1.289706,0.514545,1.051438,0.996434,2114.078357,9.501462,225.534972,1.837357,...,367.331640,267.330617,0.060322,107.835223,4.895505,71737.829286,63.976956,41.942817,1.418901,17.850780
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.990000,1.000000,0.220000,0.000000,...,0.300000,0.270000,0.300000,0.000000,0.000000,0.000000,0.010000,0.000000,0.000000,0.000000
25%,125000.750000,1.000000,1.000000,1.000000,1.000000,1.000000,400.440000,5.000000,38.790000,0.000000,...,247.850000,160.220000,0.881600,95.430000,0.000000,0.000000,25.220000,7.110000,0.000000,0.000000
50%,250000.500000,2.000000,1.000000,1.000000,1.000000,2.000000,686.425000,10.000000,74.980000,0.000000,...,432.720000,291.460000,0.923500,154.760000,0.000000,0.000000,49.740000,15.800000,0.000000,1.300000
75%,375000.250000,2.000000,1.000000,1.000000,1.000000,3.000000,1103.930000,15.000000,154.782500,0.000000,...,694.760000,482.030000,0.966400,230.820000,0.000000,0.000000,88.310000,31.370000,0.000000,6.500000
max,500000.000000,8.000000,11.000000,5.000000,9.000000,7.000000,53253.220000,78.000000,5647.790000,14.000000,...,4178.700000,3348.290000,1.221700,1065.360000,39.000000,499991.000000,1026.680000,942.190000,11.000000,100.000000

In [5]:
df[df.isnull().any(axis=1)]

,id_cliente,nome,sobrenome,email,telefone,data_cadastro,pais_registro,pais_ip_ultima_transacao,geolocalizacao_inconsistente,uso_vpn_proxy,...,flag_estruturacao,flag_multiplas_contas,flag_chip_dumping,flag_padrao_baixo_risco_lavagem,flag_saque_rapido,flag_suspeita_lavagem_dinheiro,status_investigacao,status_conta,pendente_validacao_documento,data_ultimo_alerta
0,1,Vitor,Ferreira,vitor.ferreira3033@outlook.com,(41) 99328-4419,2024-09-29,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Em análise,Não,NaN
1,2,Renata,Azevedo,renata.azevedo3881@hotmail.com,(47) 93523-5665,2025-03-27,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Inativo,Não,NaN
2,3,Beatriz,Azevedo Costa,beatriz.azevedo5364@outlook.com,(98) 99399-4124,2026-04-02,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Ativo,Sim,NaN
3,4,Nicolas,Teixeira Oliveira,nicolas.teixeira4172@outlook.com,(51) 92299-7466,2024-10-31,Panamá,Panamá,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Ativo,Não,NaN
4,5,Larissa,Oliveira,larissa.oliveira9626@terra.com.br,(71) 94163-6182,2024-05-02,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Ativo,Não,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,499996,Luana,Martins,luana.martins1953@icloud.com,(62) 99686-8927,2024-01-02,Paraguai,Paraguai,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Ativo,Não,NaN
499996,499997,Cláudio,Lima,claudio.lima4125@bol.com.br,(41) 92265-4877,2026-01-13,Malta,Malta,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Ativo,Sim,NaN
499997,499998,Amanda,Oliveira Cardoso,amanda.oliveira5138@bol.com.br,(71) 92239-7698,2024-02-24,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Ativo,Não,NaN
499998,499999,Luana,Campos,luana.campos531@bol.com.br,(31) 97364-6876,2025-01-26,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Inativo,Não,NaN
499999,500000,Paulo,Farias,paulo.farias2290@gmail.com,(98) 92621-4526,2025-12-18,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Inativo,Não,NaN

In [6]:
df

,id_cliente,nome,sobrenome,email,telefone,data_cadastro,pais_registro,pais_ip_ultima_transacao,geolocalizacao_inconsistente,uso_vpn_proxy,...,flag_estruturacao,flag_multiplas_contas,flag_chip_dumping,flag_padrao_baixo_risco_lavagem,flag_saque_rapido,flag_suspeita_lavagem_dinheiro,status_investigacao,status_conta,pendente_validacao_documento,data_ultimo_alerta
0,1,Vitor,Ferreira,vitor.ferreira3033@outlook.com,(41) 99328-4419,2024-09-29,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Em análise,Não,NaN
1,2,Renata,Azevedo,renata.azevedo3881@hotmail.com,(47) 93523-5665,2025-03-27,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Inativo,Não,NaN
2,3,Beatriz,Azevedo Costa,beatriz.azevedo5364@outlook.com,(98) 99399-4124,2026-04-02,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Ativo,Sim,NaN
3,4,Nicolas,Teixeira Oliveira,nicolas.teixeira4172@outlook.com,(51) 92299-7466,2024-10-31,Panamá,Panamá,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Ativo,Não,NaN
4,5,Larissa,Oliveira,larissa.oliveira9626@terra.com.br,(71) 94163-6182,2024-05-02,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Ativo,Não,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,499996,Luana,Martins,luana.martins1953@icloud.com,(62) 99686-8927,2024-01-02,Paraguai,Paraguai,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Ativo,Não,NaN
499996,499997,Cláudio,Lima,claudio.lima4125@bol.com.br,(41) 92265-4877,2026-01-13,Malta,Malta,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Ativo,Sim,NaN
499997,499998,Amanda,Oliveira Cardoso,amanda.oliveira5138@bol.com.br,(71) 92239-7698,2024-02-24,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Ativo,Não,NaN
499998,499999,Luana,Campos,luana.campos531@bol.com.br,(31) 97364-6876,2025-01-26,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Inativo,Não,NaN
499999,500000,Paulo,Farias,paulo.farias2290@gmail.com,(98) 92621-4526,2025-12-18,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Inativo,Não,NaN

In [7]:
# Risk-to-no-risk ratio

df.flag_suspeita_lavagem_dinheiro.value_counts()

flag_suspeita_lavagem_dinheiro
Não    477577
Sim     22423
Name: count, dtype: int64

In [8]:
(22423 / 477577) * 100

4.695159105233293

Although the data is exactly as I received it from Claude when I asked him to generate the CSV, in an online betting site, the actual risk of money laundering or fraud in casinos is very low in relation to the total amount of bets.

The data presented indicates a suspected money laundering risk of approximately 4.69% in relation to the casino's total.

Initially, I decided to start by directly running the prediction models, as processing the data could harm the model. I will run three simple anti-money laundering models and observe the results. If they are satisfactory, I will not process the data; otherwise, I will look at the data.

Why did I choose not to modify the data?

The data already came in a direct proportion and very close to the reality I observe daily as a risk analyst. Numerous alerts arrive daily, and practically none indicate money laundering or fraud in the casino, whether SLOT or live.

Therefore, based on my daily experience, I've decided that the best option is not to process the data, as I consider it to be in a good distribution.

In [9]:
df1 = df.copy()

In [10]:
df1

,id_cliente,nome,sobrenome,email,telefone,data_cadastro,pais_registro,pais_ip_ultima_transacao,geolocalizacao_inconsistente,uso_vpn_proxy,...,flag_estruturacao,flag_multiplas_contas,flag_chip_dumping,flag_padrao_baixo_risco_lavagem,flag_saque_rapido,flag_suspeita_lavagem_dinheiro,status_investigacao,status_conta,pendente_validacao_documento,data_ultimo_alerta
0,1,Vitor,Ferreira,vitor.ferreira3033@outlook.com,(41) 99328-4419,2024-09-29,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Em análise,Não,NaN
1,2,Renata,Azevedo,renata.azevedo3881@hotmail.com,(47) 93523-5665,2025-03-27,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Inativo,Não,NaN
2,3,Beatriz,Azevedo Costa,beatriz.azevedo5364@outlook.com,(98) 99399-4124,2026-04-02,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Ativo,Sim,NaN
3,4,Nicolas,Teixeira Oliveira,nicolas.teixeira4172@outlook.com,(51) 92299-7466,2024-10-31,Panamá,Panamá,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Ativo,Não,NaN
4,5,Larissa,Oliveira,larissa.oliveira9626@terra.com.br,(71) 94163-6182,2024-05-02,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Ativo,Não,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,499996,Luana,Martins,luana.martins1953@icloud.com,(62) 99686-8927,2024-01-02,Paraguai,Paraguai,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Ativo,Não,NaN
499996,499997,Cláudio,Lima,claudio.lima4125@bol.com.br,(41) 92265-4877,2026-01-13,Malta,Malta,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Ativo,Sim,NaN
499997,499998,Amanda,Oliveira Cardoso,amanda.oliveira5138@bol.com.br,(71) 92239-7698,2024-02-24,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Ativo,Não,NaN
499998,499999,Luana,Campos,luana.campos531@bol.com.br,(31) 97364-6876,2025-01-26,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Inativo,Não,NaN
499999,500000,Paulo,Farias,paulo.farias2290@gmail.com,(98) 92621-4526,2025-12-18,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Inativo,Não,NaN

In [11]:
df1

,id_cliente,nome,sobrenome,email,telefone,data_cadastro,pais_registro,pais_ip_ultima_transacao,geolocalizacao_inconsistente,uso_vpn_proxy,...,flag_estruturacao,flag_multiplas_contas,flag_chip_dumping,flag_padrao_baixo_risco_lavagem,flag_saque_rapido,flag_suspeita_lavagem_dinheiro,status_investigacao,status_conta,pendente_validacao_documento,data_ultimo_alerta
0,1,Vitor,Ferreira,vitor.ferreira3033@outlook.com,(41) 99328-4419,2024-09-29,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Em análise,Não,NaN
1,2,Renata,Azevedo,renata.azevedo3881@hotmail.com,(47) 93523-5665,2025-03-27,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Inativo,Não,NaN
2,3,Beatriz,Azevedo Costa,beatriz.azevedo5364@outlook.com,(98) 99399-4124,2026-04-02,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Ativo,Sim,NaN
3,4,Nicolas,Teixeira Oliveira,nicolas.teixeira4172@outlook.com,(51) 92299-7466,2024-10-31,Panamá,Panamá,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Ativo,Não,NaN
4,5,Larissa,Oliveira,larissa.oliveira9626@terra.com.br,(71) 94163-6182,2024-05-02,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Ativo,Não,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,499996,Luana,Martins,luana.martins1953@icloud.com,(62) 99686-8927,2024-01-02,Paraguai,Paraguai,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Ativo,Não,NaN
499996,499997,Cláudio,Lima,claudio.lima4125@bol.com.br,(41) 92265-4877,2026-01-13,Malta,Malta,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Ativo,Sim,NaN
499997,499998,Amanda,Oliveira Cardoso,amanda.oliveira5138@bol.com.br,(71) 92239-7698,2024-02-24,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Ativo,Não,NaN
499998,499999,Luana,Campos,luana.campos531@bol.com.br,(31) 97364-6876,2025-01-26,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Inativo,Não,NaN
499999,500000,Paulo,Farias,paulo.farias2290@gmail.com,(98) 92621-4526,2025-12-18,Brasil,Brasil,Não,Não,...,Não,Não,Não,Não,Não,Não,Nenhuma,Inativo,Não,NaN

In [12]:
encodar = ['data_cadastro',
    'id_cliente',
    'nome',
    'sobrenome',
    'email',
    'telefone',
    'data_ultimo_alerta',
    'score_risco_aml',
    'status_investigacao',
    'numero_alertas_compliance',
    'status_conta',
     'flag_estruturacao',
    'flag_multiplas_contas',
    'flag_chip_dumping',
    'flag_padrao_baixo_risco_lavagem',
    'flag_saque_rapido',
    'status_investigacao',
    'numero_alertas_compliance']

In [13]:
df1 = df1.drop(columns=encodar)

In [14]:
df1

,pais_registro,pais_ip_ultima_transacao,geolocalizacao_inconsistente,uso_vpn_proxy,numero_dispositivos_distintos,numero_contas_mesmo_dispositivo,numero_contas_mesmo_documento,numero_contas_mesmo_metodo_pagamento,numero_metodos_pagamento_distintos,valor_deposito_total,...,valor_ganho_cassino,valor_ganho_sportbook,razao_ganho_aposta_cassino,desvio_padrao_valor_aposta,numero_apostas_espelhadas,id_conta_relacionada_suspeita,bonus_usados,bonus_ganhos,flag_suspeita_lavagem_dinheiro,pendente_validacao_documento
0,Brasil,Brasil,Não,Não,2,1,1,1,3,878.43,...,346.65,539.73,0.9292,103.66,0,0,2.70,1.40,Não,Não
1,Brasil,Brasil,Não,Não,2,1,1,1,1,881.99,...,834.88,110.36,0.9515,281.51,0,0,40.74,13.91,Não,Não
2,Brasil,Brasil,Não,Não,2,1,1,1,3,228.34,...,222.91,146.40,0.8201,268.21,0,0,46.95,15.09,Não,Sim
3,Panamá,Panamá,Não,Não,2,1,1,1,1,947.45,...,183.91,745.14,0.8522,352.13,0,0,44.60,21.17,Não,Não
4,Brasil,Brasil,Não,Não,2,1,1,1,1,546.37,...,157.66,351.60,0.8091,140.45,0,0,95.83,37.93,Não,Não
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,Paraguai,Paraguai,Não,Não,2,1,1,1,2,147.06,...,378.09,101.20,0.9501,155.21,0,0,129.72,22.55,Não,Não
499996,Malta,Malta,Não,Não,1,1,1,1,2,360.40,...,764.01,46.91,0.7975,55.95,0,0,53.59,14.17,Não,Sim
499997,Brasil,Brasil,Não,Não,1,1,1,1,3,863.27,...,107.95,578.90,1.0621,332.92,0,0,44.27,18.96,Não,Não
499998,Brasil,Brasil,Não,Não,2,1,1,1,3,794.08,...,613.65,369.52,0.9795,315.15,0,0,121.53,28.67,Não,Não
499999,Brasil,Brasil,Não,Não,1,1,1,1,3,801.16,...,1719.44,381.37,0.9124,202.09,0,0,31.98,6.76,Não,Não

After correcting the error I sent to the machine learning model, which was already sending some responses for training, thus biasing the model with responses that shouldn't have been sent for problem analysis,

I applied a faster data transformation method. This prevents the model from interpreting some data points as being superior to others by a simple 1, 2, or 5.

Now I will train the model again, running it with a naive Bayesian dataset and a simple neural network to compare the performance of both models, aiming for higher performance and lower hardware consumption.

In [15]:
df1

,pais_registro,pais_ip_ultima_transacao,geolocalizacao_inconsistente,uso_vpn_proxy,numero_dispositivos_distintos,numero_contas_mesmo_dispositivo,numero_contas_mesmo_documento,numero_contas_mesmo_metodo_pagamento,numero_metodos_pagamento_distintos,valor_deposito_total,...,valor_ganho_cassino,valor_ganho_sportbook,razao_ganho_aposta_cassino,desvio_padrao_valor_aposta,numero_apostas_espelhadas,id_conta_relacionada_suspeita,bonus_usados,bonus_ganhos,flag_suspeita_lavagem_dinheiro,pendente_validacao_documento
0,Brasil,Brasil,Não,Não,2,1,1,1,3,878.43,...,346.65,539.73,0.9292,103.66,0,0,2.70,1.40,Não,Não
1,Brasil,Brasil,Não,Não,2,1,1,1,1,881.99,...,834.88,110.36,0.9515,281.51,0,0,40.74,13.91,Não,Não
2,Brasil,Brasil,Não,Não,2,1,1,1,3,228.34,...,222.91,146.40,0.8201,268.21,0,0,46.95,15.09,Não,Sim
3,Panamá,Panamá,Não,Não,2,1,1,1,1,947.45,...,183.91,745.14,0.8522,352.13,0,0,44.60,21.17,Não,Não
4,Brasil,Brasil,Não,Não,2,1,1,1,1,546.37,...,157.66,351.60,0.8091,140.45,0,0,95.83,37.93,Não,Não
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,Paraguai,Paraguai,Não,Não,2,1,1,1,2,147.06,...,378.09,101.20,0.9501,155.21,0,0,129.72,22.55,Não,Não
499996,Malta,Malta,Não,Não,1,1,1,1,2,360.40,...,764.01,46.91,0.7975,55.95,0,0,53.59,14.17,Não,Sim
499997,Brasil,Brasil,Não,Não,1,1,1,1,3,863.27,...,107.95,578.90,1.0621,332.92,0,0,44.27,18.96,Não,Não
499998,Brasil,Brasil,Não,Não,2,1,1,1,3,794.08,...,613.65,369.52,0.9795,315.15,0,0,121.53,28.67,Não,Não
499999,Brasil,Brasil,Não,Não,1,1,1,1,3,801.16,...,1719.44,381.37,0.9124,202.09,0,0,31.98,6.76,Não,Não

In [16]:
transform_categorical = ['pais_registro','pais_ip_ultima_transacao','geolocalizacao_inconsistente',
                         'uso_vpn_proxy','pendente_validacao_documento']

In [17]:
df2 = pd.get_dummies(
    df1, 
    columns=transform_categorical,
    dtype=int
)

In [18]:
df2

,numero_dispositivos_distintos,numero_contas_mesmo_dispositivo,numero_contas_mesmo_documento,numero_contas_mesmo_metodo_pagamento,numero_metodos_pagamento_distintos,valor_deposito_total,numero_depositos,valor_medio_deposito,numero_depositos_proximos_limite_declaracao,valor_saque_total,...,pais_ip_ultima_transacao_Panamá,pais_ip_ultima_transacao_Paraguai,pais_ip_ultima_transacao_Portugal,pais_ip_ultima_transacao_Uruguai,geolocalizacao_inconsistente_Não,geolocalizacao_inconsistente_Sim,uso_vpn_proxy_Não,uso_vpn_proxy_Sim,pendente_validacao_documento_Não,pendente_validacao_documento_Sim
0,2,1,1,1,3,878.43,8,109.80,0,317.80,...,0,0,0,0,1,0,1,0,1,0
1,2,1,1,1,1,881.99,10,88.20,0,610.79,...,0,0,0,0,1,0,1,0,1,0
2,2,1,1,1,3,228.34,16,14.27,0,88.13,...,0,0,0,0,1,0,1,0,0,1
3,2,1,1,1,1,947.45,1,947.45,0,735.73,...,1,0,0,0,1,0,1,0,1,0
4,2,1,1,1,1,546.37,5,109.27,0,172.51,...,0,0,0,0,1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,2,1,1,1,2,147.06,17,8.65,0,151.34,...,0,1,0,0,1,0,1,0,1,0
499996,1,1,1,1,2,360.40,11,32.76,0,204.66,...,0,0,0,0,1,0,1,0,0,1
499997,1,1,1,1,3,863.27,19,45.44,0,343.44,...,0,0,0,0,1,0,1,0,1,0
499998,2,1,1,1,3,794.08,6,132.35,0,0.00,...,0,0,0,0,1,0,1,0,1,0
499999,1,1,1,1,3,801.16,3,267.05,0,283.23,...,0,0,0,0,1,0,1,0,1,0

In [19]:
df2['flag_suspeita_lavagem_dinheiro'] = df2['flag_suspeita_lavagem_dinheiro'].map({'Sim': 1, 'Não': 0})

In [20]:
df2

,numero_dispositivos_distintos,numero_contas_mesmo_dispositivo,numero_contas_mesmo_documento,numero_contas_mesmo_metodo_pagamento,numero_metodos_pagamento_distintos,valor_deposito_total,numero_depositos,valor_medio_deposito,numero_depositos_proximos_limite_declaracao,valor_saque_total,...,pais_ip_ultima_transacao_Panamá,pais_ip_ultima_transacao_Paraguai,pais_ip_ultima_transacao_Portugal,pais_ip_ultima_transacao_Uruguai,geolocalizacao_inconsistente_Não,geolocalizacao_inconsistente_Sim,uso_vpn_proxy_Não,uso_vpn_proxy_Sim,pendente_validacao_documento_Não,pendente_validacao_documento_Sim
0,2,1,1,1,3,878.43,8,109.80,0,317.80,...,0,0,0,0,1,0,1,0,1,0
1,2,1,1,1,1,881.99,10,88.20,0,610.79,...,0,0,0,0,1,0,1,0,1,0
2,2,1,1,1,3,228.34,16,14.27,0,88.13,...,0,0,0,0,1,0,1,0,0,1
3,2,1,1,1,1,947.45,1,947.45,0,735.73,...,1,0,0,0,1,0,1,0,1,0
4,2,1,1,1,1,546.37,5,109.27,0,172.51,...,0,0,0,0,1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,2,1,1,1,2,147.06,17,8.65,0,151.34,...,0,1,0,0,1,0,1,0,1,0
499996,1,1,1,1,2,360.40,11,32.76,0,204.66,...,0,0,0,0,1,0,1,0,0,1
499997,1,1,1,1,3,863.27,19,45.44,0,343.44,...,0,0,0,0,1,0,1,0,1,0
499998,2,1,1,1,3,794.08,6,132.35,0,0.00,...,0,0,0,0,1,0,1,0,1,0
499999,1,1,1,1,3,801.16,3,267.05,0,283.23,...,0,0,0,0,1,0,1,0,1,0

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X = df2.drop(columns=['flag_suspeita_lavagem_dinheiro'])
y = df2['flag_suspeita_lavagem_dinheiro']

In [23]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42
)

In [24]:
from sklearn.naive_bayes import GaussianNB

In [25]:
model_bayes = GaussianNB()

In [26]:
model_bayes.fit(X_train, y_train)

GaussianNB()

In [27]:
model_bayes.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [28]:
from sklearn.metrics import accuracy_score

In [29]:
predict = model_bayes.predict(X_test)

In [30]:
accuracy_bayes = accuracy_score(y_test, predict)

In [31]:
accuracy_bayes

0.99985

The extraordinary result of 0.99985 accuracy seems good.

After several tests, removing all columns that could indicate data leakage or response bias, I believe the model is finally capturing data and patterns that can be applied to real-world cases.

Of course, I didn't have access to a real database of companies in the sector, but when I requested the CSV file from Claude, I defined criteria that we consider in our daily work analysis, identifying suspicious patterns of behavior in withdrawals, bets, and profits that deviate from the usual behavior in a real game.

I will conduct some tests and make a real decision about the model, whether it would be a good model for real-world cases or not.

In [32]:
from sklearn.metrics import classification_report, confusion_matrix

In [33]:
print(confusion_matrix(y_test, predict))

[[95435    15]
 [    0  4550]]

In [34]:
print(classification_report(y_test, predict, zero_division=0))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     95450
           1       1.00      1.00      1.00      4550

    accuracy                           1.00    100000
   macro avg       1.00      1.00      1.00    100000
weighted avg       1.00      1.00      1.00    100000

### Preliminary Conclusion of the Model

The model was developed with the objective of identifying patterns associated with possible cases of financial fraud, money laundering, and other suspicious activities in the context of online casinos and betting. The variables used aim to represent operational criteria and indicators relevant to anti-money laundering (AML) processes and risk analysis.

The preliminary results indicate potential for application as a tool to support the identification and prioritization of transactions that warrant investigation. However, the observed performance still needs to be validated through additional tests, including evaluation of generalization on independent data, analysis of false positives and false negatives, and verification of possible information leaks.

Therefore, the model is considered a promising prototype for transactional risk analysis, but its operational effectiveness is not yet proven. Its purpose is to support analysts' decision-making, not to determine in isolation whether a transaction constitutes fraud or money laundering.